/*
*   YULARK - a virtual machine written in C++
*   Copyright (C) 2025  Ekkehard Morgenstern
*
*   This program is free software: you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation, either version 3 of the License, or
*   (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*
*   NOTE: Programs created with YULARK do not fall under this license.
*
*   CONTACT INFO:
*       E-Mail: ekkehard@ekkehardmorgenstern.de
*       Mail: Ekkehard Morgenstern, Mozartstr. 1, D-76744 Woerth am Rhein,
*             Germany, Europe
*/
#include <stdlib.h>
#include <stdio.h>

int main( int argc, char** argv ) {

    printf( "%s",
        "// auto-generated by compf2src, do not modify\n\n"
        "#include <stddef.h>\n\n"
        "const char fvm_library[] =\n"
    );

    size_t cnt = 0;
    size_t x = 0;
    size_t margin = 72;

    for (;;) {
        int c = fgetc( stdin );
        if ( c == EOF ) {
            if ( x ) {
                x = 0;
                fputc( '"', stdout );
                fputc( '\n', stdout );
            }
            break;
        }
        if ( x == 0 ) fputc( '"', stdout );
        if ( c == '\"' ) { fputc( '\\', stdout ); ++x; }
        fputc( c, stdout ); ++cnt;
        ++x;
        if ( x >= margin ) {
            x = 0;
            fputc( '"', stdout );
            fputc( '\n', stdout );
        }
    }

    printf( "%s%zu%s",
        ";\n\n"
        "size_t fvm_library_size = ",
        cnt,
        ";\n\n"
    );

    return EXIT_SUCCESS;
}